version: "3"

services:
  bookstore:
    build:
      context: .
    container_name: bookstore
    volumes:
      - ./app/:/code/
    command: python web.py
    ports:
      - "5000:5000"
    environment:
      - DB_URL=${DB_URL}
    tty: true
    env_file:
      - .env
    depends_on:
      - rabbitmq
  workers:
    build:
      context: .
    restart: unless-stopped
    command:
      celery -A bookstore.core.infrastructure.celery.app worker --loglevel=debug
    environment:
      - DB_URL=${DB_URL}
      - BROKER_URL=${BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    volumes:
      - ./app/:/code/
    depends_on:
      - bookstore
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - "8080:15672"
      - "5672:5672"
